// MOVIE fetching and loading
export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_MOVIE_LOADING = "FETCH_MOVIE_LOADING";
export const FETCH_MOVIE_FINISHED = "FETCH_MOVIE_FINISHED";
export const CLEAR_MOVIE = "CLEAR_MOVIE";

// CAST fetch and load
export const FETCH_CAST = "FETCH_CAST";
export const FETCH_CAST_LOADING = "FETCH_CAST_LOADING";
export const FETCH_CAST_FINISHED = "FETCH_CAST_FINISHED";
export const CLEAR_CAST = "CLEAR_CAST";

// PERSON fetch and load
export const FETCH_PERSON = "FETCH_PERSON";
export const FETCH_PERSON_LOADING = "FETCH_PERSON_LOADING";
export const FETCH_PERSON_FINISHED = "FETCH_PERSON_FINISHED";
export const FETCH_PERSON_IMAGES = "FETCH_PERSON_IMAGES";
export const FETCH_PERSON_IMAGES_LOADING = "FETCH_PERSON_IMAGES_LOADING";
export const FETCH_PERSON_IMAGES_FINISHED = "FETCH_PERSON_IMAGES_FINISHED";
export const CLEAR_PERSON = "CLEAR_PERSON";

// PERSON MOVIES fetch and load
export const FETCH_MOVIESPERSON = "FETCH_MOVIESPERSON";
export const FETCH_MOVIESPERSON_LOADING = "FETCH_MOVIESPERSON_LOADING";
export const FETCH_MOVIESPERSON_FINISHED = "FETCH_MOVIESPERSON_FINISHED";

// MOVIES fetching and loading
export const FETCH_MOVIES_DATA = "FETCH_MOVIES_DATA";
export const FETCH_MOVIES_RECOMMENDED = "FETCH_MOVIES_RECOMMENDED";
export const FETCH_MOVIES_LOADING = "FETCH_MOVIES_LOADING";
export const FETCH_MOVIES_FINISHED = "FETCH_MOVIES_FINISHED";
export const CLEAR_MOVIES = "CLEAR_MOVIES";

// GENRES loading
export const FETCH_GENRES = "FETCH_GENRES";
export const FETCH_GENRES_LOADING = "FETCH_GENRES_LOADING";
export const FETCH_GENRES_FINISHED = "FETCH_GENRES_FINISHED";

// CONFIG get
export const GET_CONFIG = "GET_CONFIG";

// Set the selected menu on sidebar is valid
export const SELECTED_MENU = "SELECTED_MENU";
export const REMOVE_SELECTED_MENU = "REMOVE_SELECTED_MENU";

//Errors
export const INSERT_ERROR = "INSERT_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
