// MOVIE fetching and loading
export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_MOVIE_LOADING = "FETCH_MOVIE_LOADING";
export const FETCH_MOVIE_FINISHED = "FETCH_MOVIE_FINISHED";
export const CLEAR_MOVIE = "CLEAR_MOVIE";
// CAST fetch and load
export const FETCH_CAST = "FETCH_CAST";
export const FETCH_CAST_LOADING = "FETCH_CAST_LOADING";
export const FETCH_CAST_FINISHED = "FETCH_CAST_FINISHED";
// PERSON fetch and load
export const FETCH_PERSON = "FETCH_PERSON";
export const FETCH_MOVIESPERSON = "FETCH_MOVIESPERSON";
// RECOMMENDATIONS
export const FETCH_RECOMMENDATIONS = "FETCH_RECOMMENDATIONS";
// CONFIG get
export const GET_CONFIG = "GET_CONFIG";
// MOVIES fetching and loading
export const FETCH_MOVIES_DATA = "FETCH_MOVIES_DATA";
export const FETCH_MOVIES_SEARCH = "FETCH_MOVIES_SEARCH";
export const FETCH_MOVIES_RECOMMENDED = "FETCH_MOVIES_RECOMMENDED";
export const FETCH_MOVIES_LOADING = "FETCH_MOVIES_LOADING";
export const FETCH_MOVIES_FINISHED = "FETCH_MOVIES_FINISHED";
// GENRES loading
export const FETCH_GENRES = "FETCH_GENRES";
export const FETCH_GENRES_LOADING = "FETCH_GENRES_LOADING";
export const FETCH_GENRES_FINISHED = "FETCH_GENRES_FINISHED";
// Set the selected menu on sidebar is valid
export const SELECTED_MENU = "SELECTED_MENU";
export const REMOVE_SELECTED_MENU = "REMOVE_SELECTED_MENU";
//Errors
export const INSERT_ERROR = "INSERT_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
